# Generated by Django 4.2.23 on 2025-06-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FpvFlowStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dron_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('diagonal', models.IntegerField(blank=True, max_length=255, null=True)),
                ('dron_number', models.IntegerField()),
                ('dron_in', models.DateField()),
                ('dron_out', models.DateField()),
                ('who_took', models.CharField(blank=True, max_length=255, null=True)),
                ('position_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'FpvFlowStorage',
                'verbose_name_plural': 'FpvFlowStorage',
            },
        ),
    ]
