# Generated by Django 4.2.23 on 2025-06-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpvflowstorage',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
