# Generated by Django 4.2.23 on 2025-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fpvflowstorage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpvflowstorage',
            name='dron_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fpvflowstorage',
            name='dron_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fpvflowstorage',
            name='dron_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
